# MIT Licence
# Copyright 2025 feraxhp

name: KMP Config
author: feraxhp
description: 'An action to add dependencies to work with Kotlin Multiplatform'
branding:
  icon: 'settings'
  color: 'white'

inputs:
  path:
    description: 'Path to the project root'
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: 🧪 Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: 📲 Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: 🔓 chmod +x gradlew
      run: chmod +x gradlew
      shell: bash
      working-directory: ${{ inputs.path }}

# See LICENCE in the project root
# for the full licence detail.